[profile.default]
src = './src'
out = 'out'
libs = ['lib']
ffi = true
remappings = [
    "forge-std/=lib/forge-std/src/",
    "foundry-huff/=lib/foundry-huff/src/",
    "@openzeppelin/=lib/openzeppelin-contracts-08/",
    "openzeppelin-contracts-05/=lib/openzeppelin-contracts-05/contracts/",
    "openzeppelin-contracts-06/=lib/openzeppelin-contracts-06/contracts/",
    "openzeppelin-contracts-08/=lib/openzeppelin-contracts-08/contracts/"
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[rpc_endpoints]
goerli = "${RPC_URL}"

[etherscan]
goerli = { key = "${ETHERSCAN_API_KEY}" }
